name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deployjuan:
    runs-on: juan
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Asegura que tenga el historial completo

      - name: Ensure we are on main branch
        run: |
          git checkout main
          git reset --hard
          git clean -fd
          git pull origin main --ff-only

      - name: Navigate to the project directory
        run: cd disenho  # 🛠 Moverse a la carpeta correcta antes de instalar

      - name: Install dependencies and restart server
        working-directory: disenho  # 🔥 Define la carpeta donde correrán los comandos
        run: |
          npm install
          pm2 restart server

  deployandrea:
    runs-on: andrea
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure we are on main branch
        run: |
          git checkout main
          git reset --hard
          git clean -fd
          git pull origin main --ff-only

      - name: Navigate to the project directory
        run: cd disenho  # 🛠 Moverse a la carpeta correcta antes de instalar

      - name: Install dependencies and restart server
        working-directory: disenho  # 🔥 Define la carpeta donde correrán los comandos
        run: |
          npm install
          pm2 restart server

