name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deployjuan:
    runs-on: juan
    steps:
      - uses: actions/checkout@v2

      - name: Update code from GitHub
        run: git pull origin main

      - name: run server
        run: |
          npm install
          pm2 restart server

  deployandrea:
    runs-on: andrea
    steps:
      - uses: actions/checkout@v2

      - name: Update code from GitHub
        run: git pull origin main

      - name: run server
        run: |
          npm install
          pm2 restart server

