name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deployjuan:
    runs-on: juan
    steps:
      - uses: actions/checkout@v2

      - name: run server
        run: |
          npm install
          pm2 restart server

  deployandrea:
    runs-on: andrea
    steps:
      - uses: actions/checkout@v2

      - name: copy .env file
        run : cp ~/my-server/actions-runner/_work/disenho/disenho/.env .

      - name: install npm dependencies
        run:  npm install --verbose

      - name: run server
        run: |
          npm install
          pm2 restart server

      - name: verify all services are running
        run: pm2 list

  deploybrayan:
    runs-on: brayan
    steps:
      - uses: actions/checkout@v2

      - name: run server
        run: |
          npm install
          pm2 restart server

  deploysteeven:
    runs-on: steeven
    steps:
      - uses: actions/checkout@v2

      - name: run server
        run: |
          npm install
          pm2 restart server
