name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deployjuan:
    runs-on: [self-hosted, juan]
    steps:
      - uses: actions/checkout@v2

      - name: run server
        run: |
          npm install
          sudo pm2 restart server.js


  deployandrea:
    runs-on: [self-hosted, andrea]
    steps:
      - uses: actions/checkout@v2

      - name: run server
        run: |
          npm install
          sudo pm2 restart server.js

  deploybrayan:
    runs-on: [self-hosted, brayan]
    steps:
      - uses: actions/checkout@v2

      - name: run server
        run: |
          npm install
          sudo pm2 restart server.js

  deploysteeven:
    runs-on: [self-hosted, steeven]
    steps:
      - uses: actions/checkout@v2

      - name: run server
        run: |
          npm install
          sudo pm2 restart server.js
