name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deployjuan:
    runs-on: [self-hosted, juan]
    steps:
      - uses: actions/checkout@v2

      - name: run server
        run: |
          npm install
          pm2 restart server

  deployandrea:
    runs-on: [self-hosted, andrea]
    steps:
      - uses: actions/checkout@v2

      - name: run server
        run: |
          npm install
          pm2 restart server

