name: Deploy to EC2 Node.js

on:
  push:
    branches:
      - main

jobs:
  deploy_juan:
    runs-on: juan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update code on EC2
        run: |
          cd ~/disenho
          git pull origin main
          npm install

      - name: Restart Node.js server
        run: |
          cd ~/disenho
          pm2 restart all || node server.js &

  deploy_andrea:
    runs-on: andrea

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update code on EC2
        run: |
          cd ~/disenho
          git pull origin main
          npm install

      - name: Restart Node.js server
        run: |
          cd ~/disenho
          pm2 restart all || node server.js &
    
