name: Deploy to Server

on:
  push:
    branches: [main, juan, andrea, brayan, steeven]

jobs:
  deployjuan:
    runs-on: juan
    steps:
      - uses: actions/checkout@v2

      - name: install npm dependencies
        run:  npm install 

      - name: env file
        run:  cp /home/ubuntu/my-server/actions-runner/.env /home/ubuntu/my-server/actions-runner/_work/disenho/disenho/

      - name: run server
        run: |
          npm install
          pm2 restart server

      - name: verify all services are running
        run: pm2 list

  deployandrea:
    runs-on: andrea
    steps:
      - uses: actions/checkout@v2

      - name: install npm dependencies
        run:  npm install 

      - name: env file
        run:  cp /home/ubuntu/my-server/actions-runner/.env /home/ubuntu/my-server/actions-runner/_work/disenho/disenho/

      - name: run server
        run: |
          npm install
          pm2 restart server

      - name: verify all services are running
        run: pm2 list

  deploybrayan:
    if: github.ref == 'refs/heads/brayan'
    runs-on: brayan
    steps:
      - uses: actions/checkout@v2

      - name: install npm dependencies
        run:  npm install 

      - name: env file
        run:  cp /home/ubuntu/my-server/actions-runner/.env /home/ubuntu/my-server/actions-runner/_work/disenho/disenho/

      - name: run server
        env:
          PORT: 3001
          NOMBRE: Brayan
        run: |
          npm install
          pm2 start server.js --name brayan-app --watch

      - name: verify all services are running
        run: pm2 list

  deploysteeven:
    runs-on: steeven
    steps:
      - uses: actions/checkout@v2

      - name: install npm dependencies
        run:  npm install 

      - name: env file
        run:  cp /home/ubuntu/my-server/actions-runner/.env /home/ubuntu/my-server/actions-runner/_work/disenho/disenho/

      - name: run server
        run: |
          npm install
          pm2 restart server

      - name: verify all services are running
        run: pm2 list
